kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developers-generic-role-binding
  namespace: developers
subjects:
- kind: Group
  name: developers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: generic-role
  apiGroup: rbac.authorization.k8s.io