kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: generic-role
rules:
- apiGroups: ["apps", ""]
  resources: ["pods", "deployments", "secrets", "services", "replicasets"]
  verbs: ["*"]