kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shijit-core-app-binding
  namespace: shijit
subjects:
- kind: User
  name: shijit
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: shijit-core-app
  apiGroup: rbac.authorization.k8s.io