apiVersion: v1
kind: Pod
metadata:
  name: nginx-no-secret-pod
  namespace: rafa
  labels:
    app: myapp
spec:
  serviceAccountName: sa-code-with-me
  automountServiceAccountToken: false
  containers:
  - name: nginx
    image: nginx